# We plan to execute manually for tutorial purposes
trigger: none
# for production projects, the recommended trigger is peridical, once a week

pool:
  name: GCC_MIUN_VMSS
  vmImage: Canonical:0001-com-ubuntu-confidential-vm-focal:20_04-lts-gen2:latest

steps:
- script: |
    echo "Dumping environment"
    env | sort
    echo "End nvironment dump"
    echo "Running a repository script"
    ${BUILD_SOURCESDIRECTORY}/scripts/buildSagImages.sh
  displayName: 'Run a multi-line script'
