# We plan to execute manually for tutorial purposes
trigger: none
# for production projects, the recommended trigger is peridical, once a week

pool:
  name: GCC_MIUN_VMSS
  vmImage: Canonical:0001-com-ubuntu-confidential-vm-focal:20_04-lts-gen2:latest

steps:

- task: DownloadSecureFile@1
  name: secureInfo
  displayName: 'Download secure information'
  inputs:
    secureFile: 'secure.sh'

- script: |
    echo "Dumping environment"
    env | sort
    echo "End nvironment dump"
    echo "Running a repository script"
    chmod u+x ${BUILD_SOURCESDIRECTORY}/scripts/*.sh
    ${BUILD_SOURCESDIRECTORY}/scripts/buildSagImages.sh
  displayName: 'Generate Software AG image files'
