# We plan to execute manually for tutorial purposes
trigger: none
# for production projects, the recommended trigger is peridical, once a week

schedules:
- cron: "0 12 * * 0"
  displayName: Weekly Sunday build
  branches:
    include:
    - main

pool:
  name: GCC_MIUN_VMSS
  vmImage: Canonical:0001-com-ubuntu-confidential-vm-focal:20_04-lts-gen2:latest

jobs:
- job: downloadimages
  displayName: 'Download Software AG Images for given templates list'
  steps:

  - script: |
      sudo apt update
      #sudo apt install cifs-utils samba-common samba winbind
      sudo apt install cifs-utils wget apt-transport-https software-properties-common
      wget -q https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb
      # Register the Microsoft repository GPG keys
      sudo dpkg -i packages-microsoft-prod.deb
      # Update the list of packages after we added packages.microsoft.com
      sudo apt-get update
      # Install PowerShell
      sudo apt-get install -y powershell
    displayName: 'System software preparation'

  - task: DownloadSecureFile@1
    name: secureInfo
    displayName: 'Download secure information'
    inputs:
      secureFile: 'secure.sh'

  - script: |
      chmod u+x ${BUILD_SOURCESDIRECTORY}/scripts/*.sh
      ${BUILD_SOURCESDIRECTORY}/scripts/buildSagImages.sh
    displayName: 'Generate Software AG image files'
